steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "compile"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "test"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "start"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
# timeout: "0s"
