export default [
  {
    title: 'Dummy - Pesta Pizza! DANA bisa di Pizza Hut',
    date: 'Hingga 29 Des 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/256/pesta_pizza_dana_bisa_di_pizza_hut',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1573455282pizza_thumbnail.png',
    kodePromo: null,
    tags: ['dana', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 15 Okt – 29 Des 2019.',
        'Maksimum Cashback 30% sebesar Rp50.000/transaksi bagi pengguna akun DANA Premium.',
        'Maksimum Cashback 30% sebesar Rp25.000/transaksi bagi pengguna Akun DANA.',
        'Akun DANA Premium adalah pengguna DANA yang sudah verifikasi data diri melalui 3 langkah mudah & dapat menggunakan semua fitur aplikasi DANA.',
        'Akun DANA adalah pengguna DANA yang belum melakukan verifikasi data diri di aplikasi DANA.',
        'Promo tidak berlaku minimum transaksi.',
        'Promo hanya berlaku 1 kali transaksi/pengguna/merchant/bulan.',
        'Promo berlaku untuk 1 pengguna dengan 1 perangkat elektronik.',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Debit dan Kartu Kredit yang sudah terdaftar pada menu simpan kartu di aplikasi DANA.',
        'Promo hanya BERLAKU di restaurant Pizza Hut dan TIDAK BERLAKU di Pizza Hut Terminal 3 Soekarno Hatta, the Kitchen by Pizza Hut dan Pizza Hut Delivery (PHD).',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History pada aplikasi DANA.',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher.',
        'Apabila tidak mendapatkan promo, pengguna dapat mengajukan keluhan maksimal 7 (tujuh) hari setelah transaksi dilakukan.',
        'Pembayaran harus menggunakan kode QR DANA pada Mesin Scan DANA yang terdapat di kasir.',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna.',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu – waktu tanpa pemberitahuan sebelumnya.',
      ],
      cara: [
        'Kunjungi Pizza Hut Resto',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada Mesin Scan DANA di kasir.',
        'Cashback 30% akan otomatis didapatkan setelah transaksi berhasil.',
      ],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - DANA Cashback 20% di MOKA',
    date: 'Hingga 29 Des 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/223/dana_cashback_20_di_moka',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1571133632moka-20p-thumbnail.png',
    kodePromo: null,
    tags: ['dana', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 30 Sep – 29 Des 2019. ',
        'Maksimum Cashback 20% sebesar Rp10.000/transaksi untuk akun DANA Premium. ',
        'Maksimum Cashback 20% sebesar Rp5.000 /transaksi  untuk akun DANA.',
        'Promo berlaku tanpa minimum transaksi. ',
        'Promo hanya berlaku di Merchant MOKA. ',
        'Promo berlaku 1 kali/merchant/minggu. ',
        'Promo hanya berlaku untuk 1 akun dengan 1 perangkat elektronik.',
        'Akun DANA Premium adalah pengguna DANA yang sudah verifikasi data diri melalui 3 langkah mudah & dapat menggunakan semua fitur aplikasi DANA.',
        'Akun DANA adalah pengguna DANA yang belum melakukan verifikasi data diri di aplikasi DANA. ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil.',
        'Pembayaran harus menggunakan scan QR pada mesin MOKA.',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalah gunaan dari pengguna.',
        'DANA berhak meminta pengguna untuk melakukan peningkatan akun menjadi DANA Premium jika diperlukan untuk verifikasi data. ',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.',
        'Kunjungi Merchant MOKA ',
        'Tap Scan pada halaman utama aplikasi DANA dan scan  QR code pada mesin MOKA di kasir.',
        'Cashback 20% akan otomatis didapatkan setelah transaksi berhasil.',
      ],
      cara: [],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - DANA Cashback 40% di MOKA',
    date: 'Hingga 29 Des 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/222/dana_cashback_40_di_moka',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1571133518moka-40p-thumbnail.png',
    kodePromo: null,
    tags: ['dana', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 30 Sep – 29 Des 2019. ',
        'Maksimum Cashback 40% sebesar Rp20.000/transaksi untuk akun DANA Premium.',
        'Maksimum Cashback 40% sebesar Rp10.000/transaksi untuk akun DANA.',
        'Promo berlaku tanpa minimum transaksi.',
        'Promo hanya berlaku di Merchant MOKA. ',
        'Promo berlaku 1 kali/merchant/minggu. ',
        'Promo hanya berlaku untuk 1 akun dengan 1 perangkat elektronik.',
        'Akun DANA Premium adalah pengguna DANA yang sudah verifikasi data diri melalui 3 langkah mudah & dapat menggunakan semua fitur aplikasi DANA.',
        'Akun DANA adalah pengguna DANA yang belum melakukan verifikasi data diri di aplikasi DANA.',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil.',
        'Pembayaran harus menggunakan scan QR pada mesin MOKA.',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalah gunaan dari pengguna.',
        'DANA berhak meminta pengguna untuk melakukan peningkatan akun menjadi DANA Premium jika diperlukan untuk verifikasi data. ',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.',
        'Kunjungi Merchant MOKA. ',
        'Tap Scan pada halaman utama aplikasi DANA dan scan  QR code pada mesin MOKA di kasir.',
        'Cashback 40% akan otomatis didapatkan setelah transaksi berhasil.',
      ],
      cara: [],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - DANA Cashback di iSeller!',
    date: 'Hingga 29 Des 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/205/dana_cashback_di_iseller',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1569904848General-Cashback-480x270pxl-01.png',
    kodePromo: null,
    tags: ['dana', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 30 Sep – 29 Des 2019.',
        'Maksimum Cashback 30% hingga Rp10.000/transaksi tanpa minimum transaksi.',
        'Promo hanya berlaku di Merchant iSeller. ',
        'Promo berlaku 1 kali/merchant/minggu. ',
      ],
      cara: [],
    },
    minimalTransaction: 30000,
    cashback: null,
  },
  {
    title: 'Dummy - DANA Cashback Hingga Rp50rb!',
    date: 'Hingga 29 Des 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/201/dana_cashback_hingga_rp50rb',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1569812159Q4-COVER.png',
    kodePromo: null,
    tags: ['dana', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 30 Sep - 29 Dec 2019. ',
        'Promo berlaku tanpa minimum transaksi.  ',
        'Maksimum Cashback 10% sebesar Rp25.000/transaksi/minggu/merchant bagi pengguna akun DANA Premium.  ',
        'Maksimum Cashback 10% sebesar Rp15.000/transaksi/minggu/merchant bagi pengguna akun DANA. ',
        'Akun DANA Premium adalah akun yang sudah terverifikasi datanya & Akun DANA adalah akun yang belum melakukan verifikasi data. Data berupa KTP dan/atau Kartu Keluarga. 1 pengguna hanya menggunakan 1 KTP. ',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Kredit atau Kartu Debit. ',
        'Promo hanya berlaku di mitra merchant DANA berikut: Kopitiam, Maquis, Kovee VR, Autoglaze Carwash, 10Ten, PIZZA MILANO  (PMO), SPINFISH POKE HOUSE (SPH), Sekar Pala, Old Town White Coffee, Shanghai Express, Calibrew Coffee, Hao Chi Chinese Bistro, Edamame, Grain Traders, Boogie Doggie Cafe, Boogie Doggie Grooming.',
        'Khusus untuk merchant: Gain Traders pembayaran hanya dapat menggunakan Saldo DANA',
        'Kuota promo berlaku maksimum 1 kali/minggu selama periode promo. ',
        'Promo berlaku untuk 1 pengguna dan 1 perangkat elektronik. ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History pada aplikasi DANA. ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher. ',
        'Pembayaran harus menggunakan kode QR DANA pada mesin scan DANA yang terdapat di kasir. ',
        'Apabila user gagal mendapatkan promo, user dapat mengajukan keluhan maksimal 7 (tujuh) hari setelah transaksi dilakukan. ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna.  ',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.  ',
      ],
      cara: [
        'Kunjungi mitra merchant DANA berikut: Kopitiam, Maquis, Kovee VR, Autoglaze Carwash, 10Ten, PIZZA MILANO  (PMO), SPINFISH POKE HOUSE (SPH), Sekar Pala, Old Town White Coffee, Shanghai Express, Calibrew Coffee, Hao Chi Chinese Bistro, Edamame, Grain Traders, Boogie Doggie Cafe, Boogie Doggie Grooming.',
        'Pilih menu yang diinginkan. ',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir.',
        'Cashback 10% akan otomatis didapatkan setelah transaksi berhasil.',
        'Periode promo berlangsung selama 30 Sep - 29 Dec 2019.  ',
        'Promo berlaku tanpa minimum transaksi. ',
        'Cashback 10% maksimal Rp15.000 per transaksi bagi pengguna akun DANA Premium.  ',
        'Cashback 10% maksimal Rp10.000 per transaksi bagi pengguna akun DANA.',
        'Maksimal 6x cashback/pengguna/merchant/bulan.  ',
        'Berlaku hanya 1 kali cashback/hari/merchant.',
        'Akun DANA Premium adalah akun yang sudah terverifikasi datanya & Akun DANA adalah akun yang belum melakukan verifikasi data. Data berupa KTP dan/atau Kartu Keluarga. 1 pengguna hanya menggunakan 1 KTP. ',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Kredit atau Kartu Debit. ',
        'Promo hanya berlaku di mitra merchant DANA berikut: Fritato, Orchard Juice House, Senator Cafe & Bistro, Yumcha Dimsum (Grand City Group), MammaMia,',
        'Promo berlaku untuk 1 pengguna dan 1 perangkat elektronik.   ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History aplikasi DANA. ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher. ',
        'Pembayaran harus menggunakan kode QR DANA pada mesin scan DANA yang terdapat di kasir. ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna. ',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya. ',
        'Kunjungi mitra merchant DANA berikut: Fritato, Orchard Juice House, Senator Cafe & Bistro, Yumcha Dimsum (Grand City Group), MammaMia,',
        'Pilih menu yang diinginkan.  ',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir. ',
        'Cashback 10% akan otomatis didapatkan setelah transaksi berhasil.',
        'Periode promo berlangsung selama 30 Sep - 29 Dec 2019. ',
        'Promo berlaku tanpa minimum transaksi.  ',
        'Maksimum Cashback 20% sebesar Rp50.000/transaksi/bulan/merchant bagi pengguna akun DANA Premium.  ',
        'Maksimum Cashback 20% sebesar Rp25.000/transaksi/bulan/merchant bagi pengguna akun DANA. ',
        'Akun DANA Premium adalah akun yang sudah terverifikasi datanya & Akun DANA adalah akun yang belum melakukan verifikasi data. Data berupa KTP dan/atau Kartu Keluarga. 1 pengguna hanya menggunakan 1 KTP. ',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Kredit atau Kartu Debit. ',
        'Promo hanya berlaku di mitra merchant DANA berikut: Bio Medika, Kyochon, Itasuki, Kalcare, Tesate, Koba BBQ, MARTHA TILAAR SALON DAY & SPA (MTSDS), MARTHA TILAAR SHOP (MTS), VINES, Nudles, Bakerzin, Paradise Inn, Paradise Dinasty, Putu Made, Shaburi, Onokabe, Kintan Buffet, Shaburi & Kintan Buffet, Samwon House, Shabu Gin, Autoglaze Express, RS EMC Tangerang, Samwon to Go, Otten Coffee (OTTEN), RS EMC Sentul, RTL JAKARTA, Hong Kong Café, LALLA JAKARTA, Chir Chir, Sushi Sen, Miyagi, Hong Kong Sheng Kee Dessert (HKSKD), Waterbom PIK, Cozilia, Laboratorium Mahakam, Yuzuki, Damn I Love Indonesia, Yakiniku Like (PT IKI), STAR Department Store, Gioi Surabaya, Yie Thou (Makan Bareng Group), Mie Pedas Juara (Makan Bareng Group), Kata Sandi Kopi (Makan Bareng Group), Dimsum 24H (Makan Bareng Group), J Sushi (Makan Bareng Group), Kopi Yor, Ropang OTW, OTW Food Street, Your Bag Spa, Boutique Office Indonesa, Bateeq, Tamani, Hongkong Sheng Kee Kitchen, Hongkong Sheng Kee Dessert, Pho Street, Bariuma Ramen, Bakerzin Bandung, Bar.B.Q Plaza, Shaburi Kintan Bandung, Star Studio, Steak21":true,"201341983":0,"335559685":720,"335559739":160,"335559740":259}"=""> ',
        'Khusus STAR Departement Store berlaku minimum transaksi Rp150.000.',
        'Promo hanya berlaku untuk 1 kali transaksi/pengguna/merchant/bulan. ',
        'Promo berlaku untuk 1 pengguna dan 1 perangkat elektronik. ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History pada aplikasi DANA. ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher. ',
        'Pembayaran harus menggunakan kode QR DANA pada mesin scan DANA yang terdapat di kasir. ',
        'Apabila user gagal mendapatkan promo, user dapat mengajukan keluhan maksimal 7 (tujuh) hari setelah transaksi dilakukan. ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna.',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.',
        'Kunjungi mitra merchant DANA berikut: Bio Medika, Kyochon, Itasuki, Kalcare, Tesate, Koba BBQ, MARTHA TILAAR SALON DAY & SPA (MTSDS), MARTHA TILAAR SHOP (MTS), VINES, Nudles, Bakerzin, Paradise Inn, Paradise Dinasty, Putu Made, Shaburi, Onokabe, Kintan Buffet, Shaburi & Kintan Buffet, Samwon House, Shabu Gin, Autoglaze Express, RS EMC Tangerang, Samwon to Go, Otten Coffee (OTTEN), RS EMC Sentul, RTL JAKARTA, Hong Kong Café, LALLA JAKARTA, Chir Chir, Sushi Sen, Miyagi, Waterbom PIK, Cozilia, Laboratorium Mahakam, Yuzuki, Damn I Love Indonesia, Yakiniku Like (PT IKI), STAR Department Store, Gioi Surabaya, Yie Thou (Makan Bareng Group), Mie Pedas Juara (Makan Bareng Group), Kata Sandi Kopi (Makan Bareng Group), Dimsum 24H (Makan Bareng Group), J Sushi (Makan Bareng Group), Kopi Yor, Ropang OTW, OTW Food Street, Your Bag Spa, Boutique Office Indonesa, Bateeq, Tamani, Hongkong Sheng Kee Kitchen, Hongkong Sheng Kee Dessert, Pho Street, Bariuma Ramen, Bakerzin Bandung, Bar.B.Q Plaza, Shaburi Kintan Bandung, Star Studio, Steak21.":true,"201341983":0,"335559685":720,"335559739":160,"335559740":259}"=""> ',
        'Khusus STAR Departement Store berlaku minimum transaksi Rp150.000.',
        'Pilih menu yang diinginkan.  ',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir.',
        'Cashback 20% akan otomatis didapatkan setelah transaksi berhasil.',
        'Periode promo berlangsung selama 30 Sep - 29 Dec 2019. ',
        'Promo berlaku tanpa minimum transaksi.  ',
        'Maksimum Cashback 20% sebesar Rp25.000/transaksi/minggu/merchant bagi pengguna akun DANA Premium.  ',
        'Maksimum Cashback 20% sebesar Rp15.000/transaksi/minggu/merchant bagi pengguna akun DANA. ',
        'Akun DANA Premium adalah akun yang sudah terverifikasi datanya & Akun DANA adalah akun yang belum melakukan verifikasi data. Data berupa KTP dan/atau Kartu Keluarga. 1 pengguna hanya menggunakan 1 KTP. ',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Kredit atau Kartu Debit. ',
        'Promo hanya berlaku di mitra merchant DANA berikut: Ranch Market, Farmer Market, Day2day, The Gourmet by Ranch Market, Rayuan Pulau Kopi (Intrafood Group), Carvil, Ayam Bulungan, Shell, Wonder Culinary, Naga Swalayan, Le Gourmet, Chopstix, Platinum Resto & Cafe, Platinum Resto, Baso Mie Kopi, Baso Malang Karapitan, Momoiro,',
        'Khusus untuk merchant Shell, hanya berlaku untuk Shell Cihampelas, Shell Pasteur, Shell Soekarno Hatta, Shell Kota Baru Parahyangan.',
        'Kuota promo berlaku maksimum 1 kali/minggu selama periode promo. ',
        'Promo berlaku untuk 1 pengguna dan 1 perangkat elektronik. ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History pada aplikasi DANA. ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher. ',
        'Pembayaran harus menggunakan kode QR DANA pada mesin scan DANA yang terdapat di kasir. ',
        'Apabila user gagal mendapatkan promo, user dapat mengajukan keluhan maksimal 7 (tujuh) hari setelah transaksi dilakukan. ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna.  ',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.  ',
        'Kunjungi mitra merchant DANA berikut: Ranch Market, Farmer Market, Day2day, The Gourmet by Ranch Market, Rayuan Pulau Kopi (Intrafood Group), Carvil, Ayam Bulungan, Shell, Wonder Culinary, Naga Swalayan, Le Gourmet, Chopstix, Platinum Resto & Cafe, Platinum Resto, Momoiro',
        'Pilih menu yang diinginkan. ',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir.',
        'Cashback 20% akan otomatis didapatkan setelah transaksi berhasil.',
        'Periode promo berlangsung selama 30 Sep - 29 Desember 2019. ',
        'Promo berlaku tanpa minimum transaksi.',
        'Maksimum Cashback 20% sebesar Rp15.000/bulan/transaksi bagi pengguna akun DANA Premium. ',
        'Maksimum Cashback 20% sebesar Rp.10.000/bulan/transaksi bagi pengguna akun DANA.',
        'Promo hanya berlaku di: Urban Latte, Mynum, Yie Thou, Mie Pedas Juara, Kata Sandi Kopi, Dimsum 24H, J Sushi, Box O! Fish, O! Fish":true,"201341983":0,"335559685":720,"335559739":160,"335559740":240}"=""> ',
        'Akun DANA Premium adalah pengguna DANA yang sudah verifikasi data diri melalui 3 langkah mudah & dapat menggunakan semua fitur aplikasi DANA.',
        'Akun DANA adalah pengguna DANA yang belum melakukan verifikasi data diri di aplikasi DANA.',
        ' Promo hanya berlaku untuk 6 kali transaksi/pengguna/merchant/bulan.',
        'Promo hanya berlaku untuk 1 pengguna dengan 1 perangkat elektronik.',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil.',
        'Pembayaran harus menggunakan kode QR DANA pada Mesin Scan DANA yang terdapat di kasir.',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna.',
        'DANA berhak untuk meminta identitas KTP dan foto jika diperlukan untuk verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.',
        'Kunjungi Outlet Urban Latte, Mynum, Yie Thou, Mie Pedas Juara, Kata Sandi Kopi, Dimsum 24H, J Sushi, Box O! Fish, O! Fish":true,"201341983":0,"335559685":720,"335559739":160,"335559740":240}"=""> ',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir.',
        'Cashback 20% akan otomatis didapatkan setelah transaksi berhasil.',
        'Periode promo berlangsung selama 30 Sep - 29 Dec 2019.  ',
        'Promo berlaku tanpa minimum transaksi.  ',
        'Maksimum Cashback 30% sebesar Rp50.000/transaksi/bulan/merchant bagi pengguna akun DANA Premium.  ',
        'Maksimum Cashback 30% sebesar Rp25.000/transaksi/bulan/merchant bagi pengguna akun DANA. ',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Kredit atau Kartu Debit. ',
        'Akun DANA Premium adalah akun yang sudah terverifikasi datanya & Akun DANA adalah akun yang belum melakukan verifikasi data. Data berupa KTP dan/atau Kartu Keluarga. 1 pengguna hanya menggunakan 1 KTP. ',
        'Promo hanya berlaku di mitra merchant DANA berikut: Thai Street, Hartono, Pizza Hut, Pizza Marzano',
        'Promo hanya berlaku 1 kali transaksi/pengguna/merchant/bulan.',
        'Promo berlaku untuk 1 pengguna dan 1 perangkat elektronik.   ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History pada aplikasi DANA. ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher. ',
        'Apabila user gagal mendapatkan promo, user dapat mengajukan keluhan maksimal 7 (tujuh) hari setelah transaksi dilakukan. ',
        'Pembayaran harus menggunakan kode QR DANA pada mesin scan DANA yang terdapat di kasir. ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna.  ',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.  ',
        'Kunjungi mitra merchant DANA berikut: Thai Street, Hartono, Pizza Hut, Pizza Marzano',
        'Pilih menu yang diinginkan.  ',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir. ',
        'Cashback 30% akan otomatis didapatkan setelah transaksi berhasil. ',
        'Periode promo berlangsung selama 16 Sep – 27 Okt 2019. ',
        'Promo berlaku tanpa minimum transaksi.',
        'Maksimum Cashback 30% sebesar Rp50.000/minggu/transaksi bagi pengguna akun DANA Premium. ',
        'Maksimum Cashback 30% sebesar Rp30.000/minggu/transaksi bagi pengguna akun DANA.',
        'Promo hanya berlaku di: Sushi Tei Surabaya.',
        'Akun DANA Premium adalah pengguna DANA yang sudah verifikasi data diri melalui 3 langkah mudah & dapat menggunakan semua fitur aplikasi DANA.',
        'Akun DANA adalah pengguna DANA yang belum melakukan verifikasi data diri di aplikasi DANA.',
        'Promo hanya berlaku untuk 1 kali transaksi/pengguna/merchant/minggu.',
        'Promo hanya berlaku untuk 1 pengguna dengan 1 perangkat elektronik.',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil.',
        'Pembayaran harus menggunakan kode QR DANA pada Mesin Scan DANA yang terdapat di kasir.',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna.',
        'DANA berhak untuk meminta identitas KTP dan foto jika diperlukan untuk verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.',
        'Kunjungi Outlet Sushi Tei Surabaya.',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir.',
        'Cashback 30% akan otomatis didapatkan setelah transaksi berhasil.',
        'Periode promo berlangsung selama 30 Sep - 29 Dec 2019.  ',
        'Promo berlaku tanpa minimum transaksi.  ',
        'Maksimum Cashback 30% sebesar Rp25.000/transaksi/minggu/merchant bagi pengguna akun DANA Premium.  ',
        'Maksimum Cashback 30% sebesar Rp15.000/transaksi/minggu/merchant bagi pengguna akun DANA. ',
        'Akun DANA Premium adalah akun yang sudah terverifikasi datanya & Akun DANA adalah akun yang belum melakukan verifikasi data. Data berupa KTP dan/atau Kartu Keluarga. 1 pengguna hanya menggunakan 1 KTP. ',
        'Kuota promo berlaku maksimum 1 kali transaksi/pengguna/merchant/minggu selama periode promo. ',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Kredit atau Kartu Debit. ',
        "Promo hanya berlaku di mitra merchant DANA berikut: Dumdum waterpark, Beau, Rejuve, Quiznos, Kopi Oey, Kafe Betawi, Sate Senayan Express, Dcost, Divrt, Bebek Dower Resto, Pish N Posh, Genki Sushi, Kimukatsu, Dolcetto Coffee, Menya Musashi, Colette Lola, Saladstop!, DREAM STORE JOJO SIWA, PANAMA (PNM), NOSH Kitchen, Rezeki Fresh Market, Rempah Bali, Samwon Express, Hokkaido Bake Cheese Tart, Secret Recipe, Martabak Boss, Sunny Side Up Express (SSUE), Bebek BKB, Sunny Side Up (SSU), House of Omurice (HOO), Freshco Market, KIBO Cheese Cake (KIBO), Sate BKB, Express (BGE), Akademie, (BG), Tom Tom Kitchen, Khao Khao Urban Thai (KHAO), Indomen, Super Indo Supermarket, RamenYa!, Dolcetto Coffee, Maison Tatsuya, Sumoboo, The Peak Connoisseurs, Pho Street Kitchen, Taliwang Bali, Cold Stone, Krispy Kreme, Martabakku Menteng, Dynamic Bakery, Excelso, Sushi Kiosk Surabaya, Marutama Surabaya, Kimukatsu Surabaya, Ojju Surabaya, Kasoh, Toby's Estate, Daun Lada, Gempikoe, Super Grain, Saint Cinnamon, Anns Bakehouse & Creamery, Mr. Bitsy, Odysseia, Daytrans, Buana Bakery, Clairmont, Okirobox, Singapore Hainanese Chicken Rice, Glosis Restaurant (Gama Group), Five Monkeys Burger (Gama Group), Back Office Bistro (Gama Group), Oldbens Coffee, SHINTORI, Tuan Rumah, Sushi Box, Dairy Queen, Dapur Solo, Caribou Coffee, Tamani Plus, Tamani Express, Halal Guys, Negiya, Pho Street Kitchen, Burgreens, Burgreens Express, MamaTina, Senandung Alam, Ce-Wei Lamian, Cuppa Coffee, Walao-Eh, Mister Baso, Crunchaus Salad Jakarta, Crunchaus Salad Surabaya, Sapo Oriental, Sugakiya, Asia Bagoes, Bonjour Bakery & Pastry, Chili by Seroeni, Cotota, Fat Oppa Korean BBQ, Gemba Katsu, Gormeteria, Hachimaki, Her & Her, Jumbo Eatery, Kafetaria 170, Kedai 170, Kitamura, Lapar Kenyang, Mie Mapan, Ozumo (Hachimaki), Pepper's (Hachimaki), Picknick, Pochajjang, Porong Wei, QQ Kopitiam, SALD, Sei Aroma, Seroeni, Sibas, Tenno Ramen, Thai Alley, Toby's, Warung Mapan, Happiness Kitchen & Coffee, Patron, Pasarame Surabaya.",
        'Khusus untuk merchant: Salad Stop! pembayaran hanya dapat menggunakan Saldo DANA.',
        'Promo berlaku untuk 1 pengguna dan 1 perangkat elektronik.   ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History pada aplikasi DANA. ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher. ',
        'Apabila user gagal mendapatkan promo, user dapat mengajukan keluhan maksimal 7 (tujuh) hari setelah transaksi dilakukan. ',
        'Pembayaran harus menggunakan kode QR DANA pada mesin scan DANA yang terdapat di kasir. ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna.  ',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.  ',
        "Kunjungi mitra merchant DANA berikut: Dumdum waterpark, Beau, Rejuve, Quiznos, Kopi Oey, Kafe Betawi, Sate Senayan Express, Dcost, Halal Guys, Divrt, Bebek Dower Resto, Pish N Posh, Genki Sushi, Kimukatsu, Dolcetto Coffee, Menya Musashi, Colette Lola, Saladstop!, DREAM STORE JOJO SIWA, PANAMA (PNM), NOSH Kitchen, Rezeki Fresh Market, Rempah Bali, Samwon Express, Hokkaido Bake Cheese Tart, Secret Recipe, Martabak Boss, Sunny Side Up Express (SSUE), Bebek BKB, Sunny Side Up (SSU), House of Omurice (HOO), Freshco Market, KIBO Cheese Cake (KIBO), Sate BKB, Express (BGE), Akademie, (BG), Tom Tom Kitchen, Khao Khao Urban Thai (KHAO), Indomen, Super Indo Supermarket, RamenYa!, Dolcetto Coffee, Maison Tatsuya, Sumoboo, The Peak Connoisseurs, Taliwang Bali, Cold Stone, Krispy Kreme, Martabakku Menteng, Dynamic Bakery, Excelso, Sushi Kiosk Surabaya, Marutama Surabaya, Kimukatsu Surabaya, Ojju Surabaya, Kasoh, Toby's Estate, Crunchaus Surabaya, Crunchaus Jakarta, Daun Lada, Gempikoe, Super Grain, Saint Cinnamon, Anns Bakehouse & Creamery, Mr. Bitsy, Odysseia, Daytrans, Buana Bakery, Clairmont, Okirobox, Singapore Hainanese Chicken Rice, Glosis Restaurant (Gama Group), Five Monkeys Burger (Gama Group), Back Office Bistro (Gama Group), Oldbens Coffee, SHINTORI, Tuan Rumah, Sushi Box, Dairy Queen, Dapur Solo, Caribou Coffee, Tamani Plus, Tamani Express, Halal Guys, Negiya, Pho Street Kitchen, Burgreens, Burgreens Express, MamaTina, Senandung Alam, Ce-Wei Lamian, Cuppa Coffee, Walao-Eh, Mister Baso, Crunchaus Salad Jakarta, Crunchaus Salad Surabaya, Ichiban Sushi, Sapo Oriental, Sugakiya, Asia Bagoes, Bonjour Bakery & Pastry, Chili by Seroeni, Cotota, Fat Oppa Korean BBQ, Gemba Katsu, Gormeteria, Hachimaki, Her & Her, Jumbo Eatery, Kafetaria 170, Kedai 170, Kitamura, Lapar Kenyang, Mie Mapan, Ozumo (Hachimaki), Pepper's (Hachimaki), Picknick, Pochajjang, Porong Wei, QQ Kopitiam, SALD, Sei Aroma, Seroeni, Sibas, Tenno Ramen, Thai Alley, Toby's, Warung Mapan, Happiness Kitchen & Coffee, Patron, Pasarame Surabaya.",
        'Pilih menu yang diinginkan.  ',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir. ',
        'Cashback 30% akan otomatis didapatkan setelah transaksi berhasil. ',
        'Periode promo berlangsung selama 30 Sep - 29 Dec 2019.  ',
        'Promo berlaku tanpa minimum transaksi. ',
        'Cashback 30% maksimal Rp15.000 per transaksi bagi pengguna akun DANA Premium.  ',
        'Cashback 30% maksimal Rp10.000 per transaksi bagi pengguna akun DANA.',
        'Maksimal 6x cashback/pengguna/merchant/bulan.  ',
        'Berlaku hanya 1 kali cashback/hari/merchant.',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Kredit atau Kartu Debit. ',
        'Akun DANA Premium adalah akun yang sudah terverifikasi datanya & Akun DANA adalah akun yang belum melakukan verifikasi data. Data berupa KTP dan/atau Kartu Keluarga. 1 pengguna hanya menggunakan 1 KTP. ',
        'Promo hanya berlaku di mitra merchant DANA berikut: Bakso Dower Resto, Kopi Bojo, Kamu Tea, Monami, The Gade Coffee & Gold (GADE), The Dorcas - Gelateria & Coffee, King Mango Thai (KMT), Master Wok, KKuldak, Sharetea, Sharetea8, Tea Station Indonesia (TSI), Blue Lane Coffee, K-Drink, Avocado Lovers (AVLO), Kopitiam Go!, D2 bakery, Tahta Coffee, Yada Toys (YADA), Bali United Play Land, Happy Lemon, Terraland (TRL), Terrazone (TRZ), Hong Tang, Fika Kedai Kafi, Viva Health, Prima Freshmart, Tiger Sugar, Kopi 27, Kedai 27, Kafe 27, Kopi Temu Kangen, Chatuchak Thai Drinks, ShuShu, Fat Bubble,Presotea,RM Sederhana SA,Roti Bakar RONIN (Hachimaki).',
        'Khusus untuk merchant: Sharetea, Sharetea8, Blue Lane Coffee, Avocado Lovers (AVLO) dan Prima Freshmart pembayaran hanya dapat menggunakan Saldo DANA.',
        'Promo berlaku untuk 1 pengguna dan 1 perangkat elektronik.   ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History aplikasi DANA. ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher. ',
        'Pembayaran harus menggunakan kode QR DANA pada mesin scan DANA yang terdapat di kasir. ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna. ',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya. ',
        'Kunjungi mitra merchant DANA berikut: Bakso Dower Resto, Kopi Bojo, Kamu Tea, Monami, The Gade Coffee & Gold (GADE), The Dorcas - Gelateria & Coffee, King Mango Thai (KMT), Master Wok, KKuldak, Sharetea, Sharetea8, Tra Station Indonesia (TSI), Blue Lane Coffee, K-Drink, Avocado Lovers (AVLO), Kopitiam Go!, D2 bakery, Tahta Coffee, Yada Toys (YADA), Bali United Play Land, Happy Lemon, Terraland (TRL), Terrazone (TRZ), Hong Tang, Fika Kedai Kafi, Viva Health, Prima Freshmart, Tiger Sugar, Kopi 27, Kedai 27, Kafe 27, Kopi Temu Kangen, Chatuchak Thai Drinks, ShuShu, Fat Bubble,Presotea,RM Sederhana SA,Roti Bakar RONIN (Hachimaki).',
        'Pilih menu yang diinginkan.  ',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir. ',
        'Cashback 30% akan otomatis didapatkan setelah transaksi berhasil.',
        'Periode promo berlangsung selama 30 Sep - 29 Dec 2019.  ',
        'Promo berlaku tanpa minimum transaksi. ',
        'Maksimum Cashback 50% sebesar Rp25.000/transaksi/minggu/merchant bagi pengguna akun DANA Premium.  ',
        'Maksimum Cashback 50% sebesar Rp15.000/transaksi/minggu/merchant bagi pengguna akun DANA. ',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Kredit atau Kartu Debit. ',
        'Akun DANA Premium adalah akun yang sudah terverifikasi datanya & Akun DANA adalah akun yang belum melakukan verifikasi data. Data berupa KTP dan/atau Kartu Keluarga. 1 pengguna hanya menggunakan 1 KTP.',
        "Promo hanya berlaku di mitra merchant DANA berikut: SourSally, Hokben, Coffee Bean And Tea Leaf, Baskin Robbins, Gopek, Sate Khas Senayan, Summarecon MKG, Lewis & Carroll, Common Ground (Citiwalk/PIM), PUYO, Lokal, St Ali,Sensory Lab, Baji Pamai, Family Mart, Kiri Desu, Kandang Ayam, (Si) Kopi Biru, Apotik Mahakam, Apotik Senopati, Gaya Gelato, Wendys, Famous Amos, Hello Sunday, Roemah Kuliner, Sate Ayam & Kambing Megaria, Texas Chicken, Denny's, Raacha, Gokana Ramen Bar, Gokana Ramen & Teppan, Texas, Baso Mie Kopi-Gokana Ramen & Teppan, Bakso Malang Karapitan-Gokana Ramen & Teppan, Imperial Kitchen & Dimsum, Imperial Cakery, Imperial Tables, Imperial Shanghai, Imperial Mart, Imperial Steampot, Fiesta Steak, Lamian Palace, The Yumz, Happy Day, Fish&Co Surabaya, Yammie Hotplate, Doner Kebab, Abura Soba, Zenraku, Francis Bakery, Alien Entertainment, Games, King's Fun, Element Family Fun, Mr. Token, Indogame, Lula Bakery & Coffee (Gama Group), Bamboo Dimsum, Burger King, Yoshinoya, Dominos Pizza, Wingstop, Rice-Bowl, CFC, Pizza Pezzo, KFC, Bakmi GM, Carls Jr, Solaria, Asian Grill Express (Justus Group), Eastern Restaurant, Fish & Co Bandung, Fried Chicken Master, Golden Lamian, Ikkudo Ichi, Kopi Scooter, Lawson, Mangkok Ayam Setiabudi, Mangkok Ayam Festival Citylink, Pepper Lunch Bandung, Sushi Tei Bandung, Yakun Kaya Toast, Moodbooster Coffee, Ta Wan.",
        'Promo berlaku untuk 1 pengguna dan 1 perangkat elektronik.   ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History aplikasi DANA. ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher. ',
        'Pembayaran harus menggunakan kode QR DANA pada mesin scan DANA yang terdapat di kasir. ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna. ',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya. ',
        "Kunjungi mitra merchant DANA berikut: SourSally, Hokben, Bakmi GM, Coffee Bean And Tea Leaf, Baskin Robbins, Gopek, Sate Khas Senayan, Summarecon MKG, Lewis & Carroll, Common Ground (Citiwalk/PIM), PUYO, Lokal, St Ali,Sensory Lab, Baji Pamai, Family Mart, Kiri Desu, Kandang Ayam, (Si) Kopi Biru, Apotik Mahakam, Apotik Senopati, Gaya Gelato,Wendys, Famous Amos, Hello Sunday, Roemah Kuliner, Sate Ayam & Kambing Megaria, Texas Chicken, Denny's, Raacha, Gokana Ramen Bar, Gokana Ramen & Teppan, Baso Mie Kopi-Gokana Ramen & Teppan, Bakso Malang Karapitan-Gokana Ramen & Teppan, Imperial Kitchen & Dimsum, Imperial Cakery, Imperial Tables, Imperial Shanghai, Imperial Mart, Imperial Steampot, Fiesta Steak, Lamian Palace, The Yumz, Happy Day, Fish&Co Surabaya, Yammie Hotplate, Doner Kebab, Abura Soba, Zenraku, Francis Bakery, Alien Entertainment, Games, King's Fun, Element Family Fun, Mr. Token, Indogame, Lula Bakery & Coffee (Gama Group), Bamboo Dimsum, Burger King, Yoshinoya, Dominos Pizza, Wingstop, Rice-Bowl, CFC, Pizza Pezzo, KFC, Bakmi GM, Carls Jr, Solaria, Asian Grill Express (Justus Group), Eastern Restaurant, Fish & Co Bandung, Fried Chicken Master, Golden Lamian, Ikkudo Ichi, Kopi Scooter, Lawson, Mangkok Ayam Setiabudi, Mangkok Ayam Festival Citylink, Pepper Lunch Bandung, Sushi Tei Bandung, Yakun Kaya Toast, Moodbooster Coffee, Ta Wan.",
        'Pilih menu yang diinginkan.  ',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir. ',
        'Cashback 50% akan otomatis didapatkan setelah transaksi berhasil. ',
        'Periode promo berlangsung selama 30 Sep - 29 Dec 2019.  ',
        'Promo berlaku tanpa minimum transaksi. ',
        'Cashback 50% maksimal Rp15.000 per transaksi bagi pengguna akun DANA Premium.  ',
        'Cashback 50% maksimal Rp10.000 per transaksi bagi pengguna akun DANA.',
        'Maksimal 6x cashback/pengguna/merchant/bulan.  ',
        'Berlaku hanya 1 kali cashback/hari/merchant.',
        'Akun DANA Premium adalah akun yang sudah terverifikasi datanya & Akun DANA adalah akun yang belum melakukan verifikasi data. Data berupa KTP dan/atau Kartu Keluarga. 1 pengguna hanya menggunakan 1 KTP. ',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Kredit atau Kartu Debit.',
        "Promo hanya berlaku di mitra merchant DANA berikut: Zone 2000, Kopi Kenangan, GuluGulu, MOR, Auntie Anne's, D'crepes, Kopi Laka Laka , Kapal Api Corner , ABC corner, Wingz O Wingz, Hop-Hop, Kopi Kulo, Fore Coffee, Bar Urban Kitchen,Mang Rawit,Meru Coffee,XI BO BA (Kulo Group), Roti O.",
        'Khusus untuk merchant: Dcrepes pembayaran hanya dapat menggunakan Saldo DANA',
        'Promo berlaku untuk 1 pengguna dan 1 perangkat elektronik.   ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History aplikasi DANA. ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher. ',
        'Pembayaran harus menggunakan kode QR DANA pada mesin scan DANA yang terdapat di kasir. ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna. ',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya. ',
        "Kunjungi mitra merchant DANA berikut: Zone 2000, Kopi Kenangan, GuluGulu, MOR, Auntie Anne's, D'crepes, Kopi Laka Laka , Kapal Api Corner , ABC corner, Wingz O Wingz, Hop-Hop, Kopi Kulo, Fore Coffee, Bar Urban Kitchen,Mang Rawit,Meru Coffee,XI BO BA (Kulo Group), Roti O.",
        'Pilih menu yang diinginkan.  ',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir. ',
        'Cashback 50% akan otomatis didapatkan setelah transaksi berhasil. ',
        'Periode promo berlangsung selama 9 Sep - 8 Des 2019.  ',
        'Promo berlaku tanpa minimum transaksi. ',
        'Maksimum Cashback 50% sebesar Rp5.000/transaksi/hari berlaku untuk seluruh pengguna DANA.  ',
        'Metode pembayaran dapat menggunakan Saldo DANA, Kartu Kredit atau Kartu Debit. ',
        'Akun DANA Premium adalah akun yang sudah terverifikasi datanya & Akun DANA adalah akun yang belum melakukan verifikasi data. Data berupa KTP dan/atau Kartu Keluarga. 1 pengguna hanya menggunakan 1 KTP. ',
        'Promo hanya berlaku di Centrepark yang bekerjasama dengan DANA.',
        'Promo berlaku untuk 1 pengguna dan 1 perangkat elektronik.   ',
        ' Promo hanya berlaku di mitra merchant DANA berikut: Centrepark',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu History aplikasi DANA. ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher. ',
        'Apabila user gagal mendapatkan promo, user dapat mengajukan keluhan maksimal 7 (tujuh) hari setelah transaksi dilakukan. ',
        'Pembayaran harus menggunakan kode QR DANA pada mesin scan DANA yang terdapat di kasir. ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna. ',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun Premium jika diperlukan untuk tujuan verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.  ',
        'Kunjungi mitra Centrepark yang bekerja sama dengan DANA.',
        'Tap Bayar/Pay pada halaman utama aplikasi DANA dan arahkan kode QR pada mesin scan DANA di kasir. ',
        'Cashback 50% akan otomatis didapatkan setelah transaksi berhasil. ',
      ],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - DANA Cashback Hingga 25% di JumpStart',
    date: 'Hingga 08 Des 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/199/dana_cashback_hingga_25_di_jumpstart',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1569470837jumpstart-thumbnail.png',
    kodePromo: null,
    tags: ['dana', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 9 Sep – 8 Des 2019.  ',
        'Maksimum Cashback 25% hingga Rp2.500/transaksi',
        'Promo berlaku tanpa minimum transaksi.',
        'Promo hanya berlaku 1 kali transaksi/pengguna/hari. ',
        'Promo hanya berlaku untuk 1 pengguna dengan 1 perangkat elektronik.',
      ],
      cara: [],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - Bonus Voucher Classified hingga Rp50rb',
    date: 'Hingga 29 Mar 2020',
    detailUrl: 'https://www.dana.id/id/promo/detail/194/bonus_voucher_classified_hingga_rp50rb',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1568605777CLASSIFIED-THUMBNAIL.png',
    kodePromo: null,
    tags: ['dana', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 16 Sep – 29 Mar 2020. ',
        'Voucher Diskon Classified 20% didapatkan setelah pengguna melakukan minimum transaksi Rp100.000.',
        'Maksimum diskon 20% sebesar Rp50.000/transaksi berlaku untuk seluruh pengguna DANA.  ',
        'Promo hanya berlaku untuk 1 kali transaksi/pengguna/merchant/bulan. ',
        'Promo hanya berlaku untuk 1 pengguna dengan 1 perangkat elektronik. ',
      ],
      cara: [],
    },
    minimalTransaction: 20000,
    cashback: null,
  },
  {
    title: 'Dummy - Bonus Voucher Fook Yew hingga Rp50rb',
    date: 'Hingga 29 Mar 2020',
    detailUrl: 'https://www.dana.id/id/promo/detail/193/bonus_voucher_fook_yew_hingga_rp50rb',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1568605580FOOK-YEW-THUMBNAIL.png',
    kodePromo: null,
    tags: ['dana', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 16 Sep – 29 Mar 2020. ',
        'Voucher Diskon Fook Yew 20% didapatkan setelah pengguna melakukan minimum transaksi Rp100.000.',
        'Maksimum diskon 20% sebesar Rp50.000/transaksi berlaku untuk seluruh pengguna DANA.  ',
        'Promo hanya berlaku untuk 1 kali transaksi/pengguna/merchant/bulan. ',
        'Promo hanya berlaku untuk 1 pengguna dengan 1 perangkat elektronik. ',
      ],
      cara: [],
    },
    minimalTransaction: 20000,
    cashback: null,
  },
  {
    title: 'Dummy - Bonus Voucher The Duck King hingga Rp50rb',
    date: 'Hingga 29 Mar 2020',
    detailUrl: 'https://www.dana.id/id/promo/detail/192/bonus_voucher_the_duck_king_hingga_rp50rb',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1568605269DUCK-KING-THUMBNAIL.png',
    kodePromo: null,
    tags: ['dana', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 16 Sep – 29 Mar 2020. ',
        'Voucher Diskon The The Duck King 20% didapatkan setelah pengguna melakukan minimum transaksi Rp100.000.',
        'Maksimum diskon 20% sebesar Rp50.000/transaksi berlaku untuk seluruh pengguna DANA.  ',
        'Promo hanya berlaku untuk 1 kali transaksi/pengguna/merchant/bulan. ',
        'Promo hanya berlaku untuk 1 pengguna dengan 1 perangkat elektronik. ',
      ],
      cara: [],
    },
    minimalTransaction: 20000,
    cashback: null,
  },
  {
    title: 'Dummy - Beli Kode Voucher Google Play Pakai DANA, Gratis Item PUBG Mobile!',
    date: 'Hingga 30 Nov 2019',
    detailUrl:
      'https://www.dana.id/id/promo/detail/247/beli_kode_voucher_google_play_pakai_dana_gratis_item_pubg_mobile',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1572843180gpv_thumbnail.png',
    kodePromo: null,
    tags: ['dana', 'game'],
    detail: {
      syaratKetentuan: [
        'Tersedia bagi pengguna yang membeli kode Voucher Google Play di DANA mulai 1 November 2019 sampai 30 November 2019.',
        'Berlaku hanya untuk item dalam game PUBG Mobile di Google Play',
        'Item dalam game berlaku setelah pembayaran dilakukan. Tukarkan paling lambat 30 Desember 2019.',
        'Hanya terbatas untuk 3 item bagi setiap pengguna.',
        'Item dalam game PUBG Mobile berlaku setelah pembayaran dilakukan',
        'Persyaratan lengkap : https://play.google.com/intl/ALL_id/about/card-terms/',
        'Variasi Bonus Game Item:PUBG MobileNoVoucher Google PlayNama PaketItem NameQuantity1Rp20.000 - Rp50.000Erangle PackageKepala Es Krim (15h)12Rp100.000 - Rp150.000Miramar PackageKemeja Tropis Hawaii Merah (30h)1Sendal Renang (30h)13Rp300.000Sanhok PackageSetelan Luau (30h)1   Mahkota Bunga Luau (30h)1   Kupon Klasik14Rp500.000Vikendi PackageSetelan Hoodie Merah (30h)1Nutcracker - Panci (30h)1Ransel Sirkus (30h)1Kupon Klasik1',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalah gunaan dari pengguna. ',
        'DANA berhak untuk meminta identitas KTP dan foto jika diperlukan untuk verifikasi. ',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.',
      ],
      cara: [
        'Apabila user gagal mendapatkan promo, user dapat mengajukan keluhan maksimal 7 (tujuh) hari setelah transaksi dilakukan.',
      ],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - Top Up Diamond, Menangin Legendary Skin!',
    date: 'Hingga 25 Nov 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/231/top_up_diamond_menangin_legendary_skin',
    imageUrl:
      '//a.m.dana.id/danaweb/promo/promo-157198403220191016_mobile-legend-legendary-skin_web-promo-banner-01.png',
    kodePromo: null,
    tags: ['dana', 'game'],
    detail: {
      syaratKetentuan: [
        'Periode promo adalah 25 Oktober 2019 sampai dengan 25 November 2019.',
        'Setiap user yang top up diamond menggunakan dana akan mendapatkan kesempatan untuk memenangkan (1) satu Skin Legendary Mobile Legend Per hari.',
        'Pemenang Legendary Skin Mobile Legend adalah pengguna yang melakukan top up terbanyak setiap harinya.',
        'Setiap hari DANA membagikan (2) dua Legendary Skin Mobile Legend.',
        'Skin dan item yang bisa di menangkan oleh user adalah:Miya Modena ButterflyGord ConquerorSaber Codename StormAlucard Obsidian Blade',
        'Hadiah yang diberikan ke pemenang akan di masukkan ke ID user Mobile Legend setiap hari Kamis – Sabtu',
        'Untuk pemenang dari tanggal 25 Oktober– 30 Oktober akan diberikan pada tanggal 31 Oktober',
        'Untuk pemenang dari tanggal 31 November – 6 November akan diberikan pada tanggal 7 November',
        'Untuk pemenang dari tanggal 7 November – 13 November akan diberikan pada tanggal 14 November',
        'Untuk pemenang dari tanggal 14 November – 20 November akan diberikan pada tanggal 21 November',
        'Untuk pemenang dari tanggal 21 November -25 November akan diberikan pada tanggal 28 November',
        'Akan dipilih (2) dua pemenang setiap harinya selama periode promo berlangsung.',
        'Pemenang akan diumumkan di instagram story DANA @dana.id setiap harinya.',
        'Top up Diamond selama periode event berlangsung menggunakan prosedur aplikasi DANA.',
        'Transaksi harus berstatus berhasil/sukses pada periode promo.',
        'Semua keputusan oleh DANA, dan Mobile Legends adalah final.',
        'Dana id berhak menahan dan/atau membatalkan promo kepada pengguna sewaktu-waktu termasuk jika ditemukan tindak penyalahgunaan (abusive), kecurangan (fraudulent) dan/atau aktivitas mencurigakan lainnya di akun pengguna.',
        'Syarat & ketentuan promo sewaktu-waktu dapat berubah.',
      ],
      cara: [],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - Ajak Teman Pakai DANA, AUTO JUTAWAN!',
    date: 'Hingga 31 Des 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/258/ajak_teman_pakai_dana_auto_jutawan',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1573727087referral_thumbnail.png',
    kodePromo: null,
    tags: ['dana', 'entertainment'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlaku selama 15 Nov 2019 pkl. 08.00 WIB – 31 Des 2019 pkl. 23.59 WIB.',
        'Pengundang harus mengajak teman yang BELUM memiliki akun DANA (Terundang) untuk mendaftar di aplikasi DANA, menjadi DANA Premium, dan melakukan Kirim Uang.',
        'Setiap Pengundang dan Terundang akan mendapatkan Voucher DANA.',
        'Setiap Pengundang dapat mengajak teman sebanyak-banyaknya untuk mendapatkan promo.',
        'Voucher hanya berlaku untuk 1 pengguna dengan 1 perangkat elektronik.',
        'Promo berlaku untuk semua pengguna DANA.',
        'Voucher akan otomatis dikirimkan ke Pocket dan hanya dapat digunakan dengan aplikasi DANA.',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalah gunaan dari pengguna.',
        'DANA berhak meminta pengguna untuk melakukan peningkatan akun menjadi DANA Premium jika diperlukan untuk verifikasi data.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.',
      ],
      cara: [
        'Pengundang harus mengirimkan kode referral atau Kirim Uang melalui chat atau SMS ke nomor handphone teman yang BELUM memiliki akun DANA (Terundang) untuk mendaftar di aplikasi DANA, menjadi DANA Premium dan melakukan Kirim Uang.',
        'Pengundang akan mendapatkan 1 Voucher DANA setiap 1 Terundang mendaftar di aplikasi DANA, menjadi DANA Premium, dan melakukan Kirim Uang dengan Saldo DANA minimum Rp5.000.',
        'Setiap Pengundang dapat mengajak teman sebanyak-banyaknya.',
        'Pengundang akan mendapatkan Voucher DANA 100% maksimum Rp10.000.',
        'Voucher hanya berlaku untuk transaksi F&B atau Produk Digital (Pulsa/Biller/Games) di Aplikasi DANA.',
        'Voucher berlaku dengan minimum transaksi Rp10.000.',
        "Voucher DANA dapat digunakan untuk transaksi Produk Digital (Pulsa, Biller, & Games) di aplikasi DANA atau di merchant DANA berikut: KFC, Solaria, Yoshinoya, Burger King, HokBen, Pizza Hut, Kopi Kenangan, Hop-Hop, Roti’O, CFC, Bakmi GM, Domino’s Pizza, Dcrepes, Ta Wan, Ichiban Sushi, Wingstop, Gulu Gulu, Shihlin Taiwan Street Snacks, Carl’s Junior, Puyo Desserts, Sour Sally, Auntie Anne's, Wendy’s, Gokana, Platinum, BMK, Fore Coffee, Kopi Kulo, Dairy Queen, Doner Kebab, Pepper Lunch, Pezzo Pizza, Rice-Bowl, Re.juve, Dapur Solo, Kamu Tea, Cuppa Coffee, Fiesta Steak, Mister Baso, Coffee Bean & Tea Leaf, ShuShu, Sate Khas Senayan, Texas Chicken, Baskin Robbins, Monami, Sugakiya, D’Cost, Halal Guys, Dynamic Bakery & Cake, Bariuma, Caribou Coffee, Krispy Kreme.",
        'Voucher berlaku untuk transaksi menggunakan Saldo DANA, Kartu Debit, dan Kartu Kredit yang tersimpan melalui fitur Simpan Kartu, maupun BCA OneKlik.',
        'Voucher berlaku hingga 14 hari setelah voucher diterbitkan.',
        'Terundang harus mendaftar di aplikasi DANA, menjadi DANA Premium dan melakukan Kirim Uang dengan Saldo DANA minimum Rp5.000 untuk mendapatkan Voucher DANA.',
        'Terundang akan mendapatkan 3 voucher sebagai berikut:Setelah mendaftar aplikasi DANA, Terundang akan mendapat 1 Voucher F&B Rp10.000 dengan minimum transaksi Rp10.000.Setelah menjadi DANA Premium, Terundang akan mendapat 1 Voucher Pulsa Rp5.000 tanpa minimum transaksi.Setelah melakukan Kirim Uang dengan Saldo DANA minimum Rp5.000, Terundang akan mendapat 1 Voucher DANA 50% maksimum Rp5.000.',
        "Voucher DANA dapat digunakan untuk transaksi Produk Digital (Pulsa, Biller, & Games) di aplikasi DANA atau di merchant DANA berikut: KFC, Solaria, Yoshinoya, Burger King, HokBen, Pizza Hut, Kopi Kenangan, Hop-Hop, Roti’O, CFC, Bakmi GM, Domino’s Pizza, Dcrepes, Ta Wan, Ichiban Sushi, Wingstop, Gulu Gulu, Shihlin Taiwan Street Snacks, Carl’s Junior, Puyo Desserts, Sour Sally, Auntie Anne's, Wendy’s, Gokana, Platinum, BMK, Fore Coffee, Kopi Kulo, Dairy Queen, Doner Kebab, Pepper Lunch, Pezzo Pizza, Rice-Bowl, Re.juve, Dapur Solo, Kamu Tea, Cuppa Coffee, Fiesta Steak, Mister Baso, Coffee Bean & Tea Leaf, ShuShu, Sate Khas Senayan, Texas Chicken, Baskin Robbins, Monami, Sugakiya, D’Cost, Halal Guys, Dynamic Bakery & Cake, Bariuma, Caribou Coffee, Krispy Kreme.",
        'Voucher berlaku untuk transaksi menggunakan Saldo DANA, Kartu Debit, dan Kartu Kredit yang tersimpan melalui fitur Simpan Kartu, maupun BCA OneKlik.',
        'Setiap voucher berlaku hingga 7 hari setelah voucher diterbitkan.',
      ],
    },
    minimalTransaction: 10000,
    cashback: null,
  },
  {
    title: 'Dummy - Ada 100 Juta Setiap Hari Tanpa Diundi!',
    date: 'Hingga 09 Feb 2020',
    detailUrl: 'https://www.dana.id/id/promo/detail/249/ada_100_juta_setiap_hari_tanpa_diundi',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1572921180toracinno_thumbnail.jpg',
    kodePromo: null,
    tags: ['dana', 'entertainment'],
    detail: {
      syaratKetentuan: [
        'Periode Kompetisi Live Quiz “Auto Kaya” berlangsung setiap hari dimulai dari tangal 1 Nov 2019 sampai dengan tanggal 9 Feb 2020.',
        'Kompetisi Live Quiz “Auto Kaya” hanya berlaku bagi seluruh pengguna aplikasi Toraccino.',
        'Untuk berpartisipasi dalam kompetisi ini, peserta wajib:Memiliki 1 sachet kopi yang hanya bisa dipakai satu kali.Download aplikasi Toraccino lalu hubungkan atau daftar akun DANA di aplikasi Torracino.  ',
        'Pada setiap hari nya, akan ada 2 sesi dari kompetisi Live Quiz “Auto Kaya”:Sesi pertama dimulai pada Pukul 13.00 WIBSesi kedua dimulai pada Pukul 20.00 WIB',
        'Satu sesi Live Quiz “Auto Kaya” berdurasi 10 menit dan terdiri dari 6 pertanyaan trivia yang harus dijawab dengan memilih 1 jawaban dari 4 pilihan jawaban yang tersedia.',
        'Untuk memenangkan hadiah Saldo DANA, peserta diharuskan untuk menjawab dengan benar semua pertanyaan pada sesi Live Quiz “Auto Kaya” tersebut.',
        'Hadiah Kompetisi Live Quiz “Auto Kaya” dengan rincian berupa:Total saldo DANA senilai Rp50.000.000 yang akan dibagikan kepada para pemenang setiap hari sejak tanggal 1 Nov 2019 – 11 Nov 2019.Total saldo DANA senilai Rp100.000.000 yang akan dibagikan kepada para pemenang setiap hari sejak tanggal 12 Nov 2019 – 9 Feb 2020.',
        'Hadiah kompetisi berupa Saldo DANA yang berhasil didapatkan pemenang akan langsung diberikan melalui Akun DANA terdaftar, selambat-lambatnya 7 hari kerja setelah sesi berakhir.',
        'Apabila hadiah belum berhasil diterima oleh pemenang, pihak DANA akan menghubungi pemenang sebanyak 3 kali. Apabila tidak ada jawaban dari pemenang, hadiah akan dianggap hangus.',
        'Pemenang Kompetisi akan diumumkan secara langsung melalui Inbox dan Leaderboard dalam aplikasi Toraccino setelah sesi kuis berakhir selama periode kompetisi Live Quiz “Auto Kaya” berlangsung.',
        'Promo hanya berlaku untuk 1 pengguna dengan 1 perangkat elektronik.',
        'Berlaku ketentuan 1 akun DANA dengan 1 identitas KTP bagi pemenang Kompetisi.',
        'Kompetisi hanya berlaku untuk Warga Negara Indonesia.',
        'Untuk 1 akun hanya berkesempatan menjadi pemenang Kompetisi sebanyak 1 kali untuk masing-masing sesi Live Quiz “Auto Kaya”.',
        'Penentuan pemenang berdasarkan peserta yang berhasil menjawab semua pertanyaan dengan benar.',
        'Keputusan mengenai penentuan pemenang dan hal-hal lain yang terkait dengan kompetisi adalah mutlak kewenangan DANA yang bersifat final dan tidak dapat diganggu gugat.',
        'Dengan mengikuti kompetisi ini, peserta dinyatakan telah membaca dan memahami, serta setuju untuk mematuhi dan menaati syarat dan ketentuan serta perubahan-perubahannya (jika ada).',
        'Jika terdapat hal-hal yang menurut pertimbangan DANA, pemenang tidak mentaati syarat dan ketentuan yang telah ditentukan atau mengandung unsur pelanggaran hukum dan ketentuan yang berlaku, maka DANA berhak meninjau kembali atau membatalkan secara sepihak hak dari pemenang untuk mendapatkan hadiah.Atas hal tersebut peserta wajib menerima dan tidak akan melakukan tuntutan kepada DANA dalam bentuk apapun.',
        'DANA berhak mengubah syarat dan ketentuan jika dianggap perlu.',
        'Hadiah tidak dapat ditukarkan dalam bentuk selain yang disediakan oleh DANA, tidak dapat dipindahtangankan atau diuangkan.',
        'DANA berhak meminta pengguna untuk melakukan peningkatan akun menjadi DANA Premium jika diperlukan untuk verifikasi data.',
        'Syarat dan ketentuan dapat berubah sewaktu – waktu tanpa pemberitahuan sebelumnya.',
      ],
      cara: ['Untuk informasi lebih lanjut kunjungi situs resmi Toraccino di www.toraccino.co.id'],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - Kejutan Hadiah #Puas11Rupiah',
    date: 'Hingga 30 Nov 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/239/kejutan_hadiah_puas11rupiah',
    imageUrl:
      '//a.m.dana.id/danaweb/promo/promo-15728502291111PRIZEDISTRIBUTION_WEBSITETHUMBNAIL_480X270.png',
    kodePromo: null,
    tags: ['dana', 'entertainment'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 8 - 11 Nov 2019.',
        'Setiap pembelian Voucher Rp11 F&B, pengguna secara otomatis berkesempatan memenangkan hadiah:Samsung Note10+ untuk 15 pemenang dari pembelian voucher:',
        'Setiap pengguna hanya dapat memenangkan 1 hadiah selama periode promo.',
        'Promo berlaku untuk 1 pengguna dengan 1 perangkat elektronik.',
        'Pemenang akan mendapatkan hadiah berdasarkan ketersediaan warna & tipe hadiah.',
        'Proses penentuan pemenang dilakukan di kantor DANA pada tanggal 19 Nov 2019 (Gd. Capital Place Office Tower Lt. 18, Jl. Jend. Gatot Subroto Kav. 18, Kel. Kuningan Barat, Kec. Mampang Prapatan, Kota Administrasi Jakarta Selatan 12710) bersama dengan pihak Dinas Sosial.',
        'Pemenang akan diumumkan melalui fitur IG Story @dana.id pada 21 Nov 2019 pukul 20.00 WIB.',
        'Pemenang akan langsung diinformasikan oleh tim DANA melalui SMS.',
        'Apabila pemenang tidak memberikan jawaban dalam rentang 30 hari kerja sejak diinformasikan oleh pihak DANA, pemenang dianggap gugur.',
        'Pajak hadiah ditanggung sepenuhnya oleh pemenang.',
        'Bagi pemenang berdomisili di Jabodetabek, pengambilan hadiah harus dilakukan di kantor DANA (Gd. Capital Place Office Tower Lt. 18, Jl. Jend. Gatot Subroto Kav. 18, Kel. Kuningan Barat, Kec. Mampang Prapatan, Kota Administrasi Jakarta Selatan 12710). Jika  pemenang berada di luar Jabodetabek, hadiah akan dikirimkan dengan kurir dari pihak ketiga dengan ongkos kirim ditanggung oleh DANA. Estimasi pengiriman hadiah dilakukan dalam rentang waktu maksimal 30 hari kerja.',
        'Bagi pemenang di wilayah Jabodetabek, wajib menyertakan identitas diri saat pengambilan hadiah di kantor DANA. Bagi pemenang di luar wilayah Jabodetabek, wajib memberikan identitas diri melalui fitur Direct Message (DM) Instagram sebagai syarat pengiriman hadiah ke alamat pemenang.',
        'Keputusan DANA mengenai penentuan pemenang dan semua hal lain yang terkait dengan Kompetisi adalah bersifat final dan tidak dapat diganggu gugat.',
        'Jika ada salah satu persyaratan Kompetisi yang tidak terpenuhi atau melanggar hukum maka DANA dapat secara sepihak membatalkan pemenang dan menyatakan pemenang gugur serta tidak berhak atas hadiah.',
        'DANA memiliki hak untuk mengubah ketentuan jika dianggap perlu tanpa pemberitahuan sebelumnya.',
        'DANA berhak untuk meminta identitas KTP dan foto diri pengguna DANA jika diperlukan untuk verifikasi.',
        'Dengan mengikuti kompetisi ini, pengguna dinyatakan telah membaca dan memahami, serta setuju untuk mematuhi dan menaati syarat dan ketentuan serta perubahan-perubahannya (jika ada).',
        'Syarat dan ketentuan ini dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.',
      ],
      cara: [],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - WOW! Ada Bonus Bulanan Buat Merchant DANA Bisnis!',
    date: 'Hingga 31 Des 2019',
    detailUrl:
      'https://www.dana.id/id/promo/detail/230/wow_ada_bonus_bulanan_buat_merchant_dana_bisnis',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1571980241thumbnail_kyb.png',
    kodePromo: null,
    tags: ['dana', 'entertainment'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 25 Okt – 31 Des 2109, pukul 13:00 hingga 23:59 WIB.',
        'Promo hanya berlaku untuk pembayaran yang menggunakan Saldo DANA dan Kartu Debit yang sudah disimpan melalui fitur Simpan Kartu di aplikasi DANA.',
        'DANA Bisnis Reward berupa cashback maksimum sebesar Rp10.000.',
        'Promo berlaku dengan minimum transaksi Rp15.000.',
        'Promo berlaku untuk 1 kali transaksi/pengguna/merchant.',
        'Kuota promo maksimum 1 kali transaksi/bulan.',
      ],
      cara: [],
    },
    minimalTransaction: 15000,
    cashback: null,
  },
  {
    title: 'Dummy - Bayar Langsung dapet Voucher DANA 50%!',
    date: 'Hingga 30 Nov 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/225/bayar_langsung_dapet_voucher_dana_50',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1571214505digital-thumbnail.png',
    kodePromo: null,
    tags: ['dana', 'entertainment'],
    detail: {
      syaratKetentuan: [
        'Period promo berlaku selama 16 Okt 2019 pukul 16.00 WIB – 30 Nov 2019 dari pukul 23:59 WIB.',
        'Promo berlaku dengan bertransaksi di Aplikasi LakuEmas, Tiketux dan MyXL.',
        'Voucher yang akan didapat adalah DANA Digital Voucher 50% Maksimum 15K',
        'Minimum transaksi untuk mendapatkan voucher adalah Rp50.000.',
        'Untuk merchant LakuEmas dan Tiketux, promo berlaku untuk setiap pengguna/2x/bulan.',
        'Untuk merchant MyXL, promo berlaku untuk seiap pengguna 1x/bulan.',
        'Voucher hanya berlaku untuk 1 pengguna dengan 1 perangkat elektronik.',
        'Tidak ada minimum pembelian untuk menggunakan voucher',
        'Untuk mendapatkan voucher tidak bisa digabungkan dengan promo lainnya.',
        'Voucher berlaku hingga 10 hari setelah voucher diterbitkan.',
        'Voucher hanya berlaku untuk pembelian produk Pulsa, Biller dan Gaming di aplikasi DANA.',
        'Promo hanya berlaku untuk semua pengguna DANA.',
        'Voucher akan otomatis dikirimkan ke akun DANA pada Pocket dan hanya dapat digunakan dengan aplikasi DANA.',
        'Voucher akan didapatkan jika kuota promo masih tersedia.',
        'Apabila user gagal mendapatkan promo, user dapat mengajukan keluhan maksimal 7 (tujuh) hari setelah transaksi dilakukan.',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalah gunaan dari pengguna.',
        'DANA berhak meminta pengguna untuk melakukan peningkatan akun menjadi DANA Premium jika diperlukan untuk verifikasi data.',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.',
      ],
      cara: [
        'Pilih Produk Digital di Aplikasi DANA.',
        'Pilih DANA sebagai metode pembayaran.',
        'Voucher akan otomatis memberikan potongan',
        'Selamat berbelanja!',
      ],
    },
    minimalTransaction: 50000,
    cashback: null,
  },
  {
    title: 'Dummy - Menangin Gadget Keren, Subscribe dan Komen di Youtube DANA!',
    date: 'Hingga 27 Des 2019',
    detailUrl:
      'https://www.dana.id/id/promo/detail/224/menangin_gadget_keren_subscribe_dan_komen_di_youtube_dana',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1571643619youtube-activation-web-banner-2.png',
    kodePromo: null,
    tags: ['dana', 'entertainment'],
    detail: {
      syaratKetentuan: [
        'Periode Kompetisi “Menangin Gadget Keren + Saldo DANA” berlangsung selama 16 Okt - 27 Des 2019.',
        'Kompetisi “Menangin Gadget Keren + Saldo DANA” hanya berlaku di Channel Youtube DANA Indonesia.',
        'Kompetisi berlaku bagi seluruh subscriber akun Youtube DANA Indonesia.',
        'Total hadiah Kompetisi “Menangin Gadget Keren + Saldo DANA” untuk 53 orang pemenang yang berlaku di dalam video Pertolongan PerDANA Paling Kekinian dengan rincian berupa: ',
        'Total hadiah Kompetisi “Menangin Gadget Keren + Saldo DANA” untuk 100 orang pemenang yang berlaku di dalam video DANA Dalam Berita dengan rincian berupa:Saldo DANA masing-masing senilai Rp50.000 untuk 20 orang pemenang yang dibagikan setiap minggu.',
        'Untuk berpartisipasi dalam kompetisi ini, pengguna wajib: Subscribe Channel Youtube DANA Indonesia.Menulis komentar berdasarkan tema pada setiap content video di kolom komentar beserta dengan akun Instagram pribadi.',
        'Batas terakhir pemberian komentar adalah 7 (tujuh) hari setelah video tersebut diunggah di channel Youtube DANA, pada pukul 18.00 WIB.',
        'Pemenang akan diumumkan 14 hari setelah video diunggah di channel Youtube DANA Indonesia.',
        'Hadiah akan diberikan selambat-lambatnya 14 hari kerja setelah pengumuman pemenang.',
        'Pemenang Kompetisi akan diumumkan melalui Community Page (Halaman Komunitas) akun Youtube DANA Indonesia dan juga di Instagram Story DANA (@dana.id) pada pukul 17.00 WIB selama periode kompetisi “Menangin Gadget Keren + Saldo DANA” berlangsung.',
        'Pemenang kompetisi akan dihubungi langsung oleh DANA dengan me-reply/membalas masing-masing komentar di dalam video yang diberikan, serta melalui fitur Direct Message (DM) Instagram DANA (@dana.id).',
        'Berlaku ketentuan 1 akun Youtube dengan 1 identitas KTP bagi pemenang Kompetisi.',
        'Kompetisi hanya berlaku untuk Warga Negara Indonesia.',
        'Untuk 1 (satu) akun subscriber hanya berkesempatan menjadi pemenang Kompetisi sebanyak 1 (satu) kali untuk masing-masing jenis video.',
        'Pajak hadiah ditanggung sepenuhnya oleh pemenang.',
        'Pemenang tidak dapat memilih warna dan/atau tipe hadiah yang diberikan. Warna dan/atau tipe hadiah akan disesuaikan dengan ketersediaan barang.',
        'Penentuan pemenang bedasarkan komentar subscriber yang dipilih oleh DANA yang ber-alamat di Gedung Capital Place, Lantai 18 Jalan Jenderal Gatot Subroto Kav 18 Jakarta Selatan (Kantor DANA).',
        'Keputusan mengenai penentuan pemenang dan semua hal lain yang terkait dengan kompetisi adalah bersifat final dan tidak dapat diganggu gugat.',
        'Pemenang kompetisi “Menangin Gadget Keren + Saldo DANA” yang berdomisili di JABODETABEK wajib menyertakan identitas diri (KTP asli) pada saat pengambilan hadiah.',
        'Dengan mengikuti kompetisi ini, pengguna dinyatakan telah membaca dan memahami, serta setuju untuk mematuhi dan menaati syarat dan ketentuan serta perubahan-perubahannya (jika ada).',
        'Jika terdapat satu dan lain hal yang menurut pertimbangan DANA pemenang tidak mentaati syarat dan ketentuan yang telah ditentukan atau mengandung unsur pelanggaran hukum dan ketentuan yang berlaku maka DANA berhak meninjau kembali atau membatalkan secara sepihak hak dari pemenang untuk mendapatkan hadiah dan atas hal tersebut maka pemenang menerima dan tidak akan melakukan tuntutan dalam bentuk apapun',
        'DANA memiliki hak untuk mengubah syarat dan ketentuan jika dianggap perlu. Segala perubahan dalam syarat dan ketentuan akan diberitahukan melalui Community Page akun Youtube (DANA Indonesia) dan juga Instagram Story DANA (@dana.id).',
        'Hadiah tidak dapat dipindahtangankan atau diuangkan.',
        'Kompetisi tidak berlaku untuk Karyawan DANA.',
        'DANA berhak untuk meminta dokumen/identitas lainnya jika diperlukan untuk verifikasi.',
        'Syarat dan ketentuan dapat berubah sewaktu – waktu tanpa pemberitahuan sebelumnya.',
      ],
      cara: [
        'Pemenang akan langsung dihubungi melalui fitur Direct Message (DM) Instagram DANA (@dana.id) dengan menyertakan data sebagai berikut:nama;ponsel;alamat e-mail;domisili;salinan KTP; dandokumen/data lain yang dianggap perlu oleh DANA.',
        'Hadiah bagi pemenang yang berdomisili di JABODETABEK, harus menyertakan identitas diri (KTP asli) saat pengambilan hadiah.',
        'Hadiah bagi pemenang yang berdomisili di LUAR JABODETABEK, akan dikirimkan berdasarkan alamat domisili.',
        'Proses pengambilan hadiah dilakukan dengan mengambil langsung di Kantor DANA, dengan biaya akomodasi menuju Kantor DANA ditanggung sendiri oleh masing-masing pemenang. Proses pengambilan hadiah DAPAT DIWAKILKAN.',
        'Proses pengambilan hadiah dilakukan 7 (tujuh) hari kerja setelah pemenang kompetisi diumumkan, pada pukul 10.00 WIB -15.00 WIB.',
      ],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - Nonton Bikin Kenyang dapat Bonus Voucher 50%!',
    date: 'Hingga 30 Nov 2019',
    detailUrl:
      'https://www.dana.id/id/promo/detail/221/nonton_bikin_kenyang_dapat_bonus_voucher_50',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1571287872mahadya-thumbnail-2.png',
    kodePromo: null,
    tags: ['dana', 'entertainment'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlaku selama 14 Okt 2019 pukul 17.00 – 30 Nov 2019 pukul 23.59.',
        'Voucher yang akan didapat adalah Voucher Diskon 50% Carl’s Jr/Wingstop/Caribou maksimal potongan Rp25.000.',
        'Khusus untuk pemesanan tiket di CGV, pembayaran hanya dapat menggunakan Saldo DANA.',
        'Voucher Diskon 50% Carl’s Jr/Wingstop/Caribou didapatkan oleh pengguna TIX ID yang melakukan transaksi pembelian tiket minimum Rp50.000 di Cinema XXI dan CGV area Jabodetabek, Surabaya, dan Bandung.',
        'Promo berlaku untuk 1 pengguna dengan 1 perangkat elektronik.',
      ],
      cara: [],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - Belanja di Bukalapak Bonus Voucher Mingguan Rp25.000',
    date: 'Hingga 30 Nov 2019',
    detailUrl:
      'https://www.dana.id/id/promo/detail/220/belanja_di_bukalapak_bonus_voucher_mingguan_rp25000',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1571042850GeneralCashback480x270pxl.png',
    kodePromo: null,
    tags: ['dana', 'entertainment'],
    detail: {
      syaratKetentuan: [
        'Buka atau kunjungi Aplikasi Bukalapak',
        'Pilih Produk Fisik atau Item Marketplace di Aplikasi Bukalapak',
        'Pilih metode pembayaran melalui saldo ataupun kartu yang sudah terdaftar di aplikasi DANA, voucher akan otomatis terpilih dan total harga akan berkurang',
        'Tap tombol "bayar" untuk selesaikan transaksi',
      ],
      cara: [],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - DANA cashback 50% di JNE!',
    date: 'Hingga 29 Des 2019',
    detailUrl: 'https://www.dana.id/id/promo/detail/218/dana_cashback_50_di_jne',
    imageUrl: '//a.m.dana.id/danaweb/promo/promo-1570589068jne-thumbnail.png',
    kodePromo: null,
    tags: ['dana', 'entertainment'],
    detail: {
      syaratKetentuan: [
        'Periode promo berlangsung selama 9 Okt – 29 Des 2019.   ',
        'Maksimum Cashback 50% sebesar Rp5.000.  ',
        'Promo berlaku untuk seluruh pengguna DANA ',
        'Promo berlaku tanpa minimum transaksi.   ',
        'Kuota promo berlaku maksimum 5 kali/minggu/merchant selama periode promo.',
        'Promo berlaku 1x per hari.',
        'Promo berlaku untuk 1 pengguna dengan 1 perangkat elektronik.   ',
        'Promo berlaku dengan metode pembayaran menggunakan Saldo DANA maupun Kartu Kredit atau Kartu Debit yang sudah disimpan melalui fitur Simpan Kartu di aplikasi DANA.   ',
        'Promo hanya berlaku diseluruh gerai JNE dan layanan kurir JNE. ',
        'Cashback akan diterima maksimum 1 x 24 jam setelah transaksi berhasil melalui menu Riwayat pada aplikasi DANA.   ',
        'Promo tetap berlaku bagi pengguna yang bertransaksi menggunakan voucher.   ',
        'Apabila pengguna gagal mendapatkan promo, pengguna dapat mengajukan keluhan maksimal 7 hari setelah transaksi dilakukan.   ',
        'DANA berhak, tanpa pemberitahuan sebelumnya, melakukan tindakan-tindakan yang diperlukan apabila diduga adanya tindakan kecurangan atau penyalahgunaan dari pengguna.    ',
        'DANA berhak meminta kepada pengguna melakukan proses peningkatan menjadi akun DANA Premium jika diperlukan untuk tujuan verifikasi.  ',
        'Syarat dan ketentuan dapat berubah sewaktu - waktu tanpa pemberitahuan sebelumnya.    ',
      ],
      cara: [
        'Kunjungi Gerai JNE atau layanan kurir JNE. ',
        'Masukan nomor telepon yang terdaftar di DANA. ',
        'Tap Bayar/Pay pada halaman kasir aplikasi DANA. ',
        'Cashback 50% akan otomatis didapatkan setelah transaksi berhasil. ',
      ],
    },
    minimalTransaction: null,
    cashback: null,
  },
  {
    title: 'Dummy - Makan Kenyang, Banyak Menang!',
    imageUrl: 'https://images-loyalty.ovo.id/public/deal/73/83/l/24675.jpg?ver=1',
    detailUrl: 'https://www.ovo.id/deals/view/24675',
    tags: ['ovo', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo 25 Oktober – 31 Desember 2019.',
        'Khusus pembayaran menggunakan OVO.',
        'Promo berlaku untuk semua transaksi (Dine-In, Takeaway, Delivery Order)',
        'WAJIB menjadi member Bakmi GM terlebih dahulu dan menyebutkan nomor member saat bertransaksi.',
        'Nomor member Bakmi GM yang terdaftar harus sama dengan nomor telepon yang terdaftar di akun OVO.',
        'Pemenang dipilih berdasarkan nilai (rupiah) transaksi selama periode program berlangsung.',
        'Pemenang wajib mengambil hadiah ditempat yang akan ditentukan oleh pihak Bakmi GM.',
        'Pemenang berdasarkan data transaksi dari OVO dan keputusan tidak dapat diganggu gugat',
        'Hadiah tidak dapat ditukar/diuangkan/dipindah tangankan.',
        'Pajak ditanggung pemenang',
      ],
      cara: [
        'Kabar baik buat kamu yang ngefans menu-menu Bakmi GM. Yuk sering-sering makan Bakmi GM, bayar pake OVO, dan menangin hadiah total senilai puluhan juta buat top spender!\n\nHadiah Utama\nSamsung Galaxy Note 10\n\nHadiah Kedua (2 orang)\nMirrorless Camera\n\nHadiah Ketiga (3 orang)\nLaptop 14"\n\nHadiah Keempat (4 orang)\nLED TV 32"\n\nHadiah Kelima (60 orang)\n200.000 OVO Points\n\nHadiah Keenam (29 orang)\nVoucher Bakmi GM 100.000\n\nNantikan pengumuman pemenang 8 Januari 2020 oleh team Bakmi GM.',
      ],
    },
    date: 'Berlaku Hingga 31 Dec 2019',
    minimalTransaction: null,
    cashback: null,
    kodePromo: null,
  },
  {
    title: 'Dummy - Maxx Out Your Weekend',
    imageUrl: 'https://images-loyalty.ovo.id/public/deal/13/86/l/24794.jpg?ver=1',
    detailUrl: 'https://www.ovo.id/deals/view/24794',
    tags: ['ovo', 'food'],
    detail: {
      syaratKetentuan: [
        'Hanya berlaku Sabtu & Minggu di semua outlet Maxx',
        'Cashback hingga 10.000 OVO Points/transaksi dan hingga 20.000 OVO Points/bulan (1 OVO Point = Rp 1)',
        'hanya berlaku untuk pembayaran dengan OVO.',
        'Berlaku untuk semua Makanan & Minuman.',
        'Periode Promo 2 - 30 November 2019.',
      ],
      cara: [
        'Maksimalin momen weekendmu dengan pesan menu kesukaan atau coba yang baru di Maxx Coffee. Pake OVO Cashback 20% buat semua makanan & minuman, setiap Sabtu & Minggu selama periode promo.',
      ],
    },
    date: 'Berlaku Hingga 30 Nov 2019',
    minimalTransaction: null,
    cashback: null,
    kodePromo: null,
  },
  {
    title: 'Dummy - All About Chocolate!',
    imageUrl: 'https://images-loyalty.ovo.id/public/deal/23/86/l/24798.jpg?ver=1',
    detailUrl: 'https://www.ovo.id/deals/view/24798',
    tags: ['ovo', 'food'],
    detail: {
      syaratKetentuan: [
        'Promo berlaku dari tanggal 08 – 21 November 2019.',
        'Promo Discount 30% dengan maksimal Discount 50.000 + Cashback 30% dengan OVO.',
        'Promo hanya berlaku di Dapur Cokelat Cikarang.',
        'Setiap transaksi minimum Rp. 10.000 menggunakan OVO Cash, berhak mendapatkan Cashback 30% dalam bentuk OVO Points.',
        'Maksimum cashback hingga 12.500 OVO Points/Transaksi dan 25.000 OVO Points/ID selama periode promo (1 OVO Points = Rp 1).',
        'OVO berhak untuk membatalkan OVO Points yang telah diberikan apabila ditemukan kecurangan dalam pelaksanaan promo ini.',
        'Jika terjadi kegagalan transaksi OVO karena alasan teknis apapun (baik EDC, jaringan koneksi atau aplikasi) maka kegagalan tersebut tidak akan menjadi tanggung jawab merchant. Konsumen wajib melakukan pelunasan pembayaran terhadap merchant ybs.',
      ],
      cara: [
        'Ngemil yang bisa bikin happy? Ngemil coklat pastinya! Mulai dari snack, praline, cake, bahkan sampe minuman, semua yang serba coklat bisa kamu dapetin di Dapur Cokelat dengan Diskon 30% + Cashback 30% pake OVO!',
      ],
    },
    date: 'Berlaku Hingga 21 Nov 2019',
    minimalTransaction: 10000,
    cashback: 30,
    kodePromo: null,
  },
  {
    title: 'Dummy - Yummy Ber 3',
    imageUrl: 'https://images-loyalty.ovo.id/public/deal/01/88/l/24878.jpg?ver=1',
    detailUrl: 'https://www.ovo.id/deals/view/24878',
    tags: ['ovo', 'food'],
    detail: {
      syaratKetentuan: [
        'Promo berlaku 08 November - 31 Desember 2019',
        'Periode penukaran / Redeem Voucher 08 November - 31 Desember 2019',
        'Khusus pembayaran menggunakan OVO CASH/POINT atau SPLIT',
        'Voucher hanya berlaku untuk pembelian 2 Beef Bowl dan 1 Big Fried Chicken',
        'Voucher yang sudah dibeli tidak dapat dikembalikan/ditukar/diuangkan  (Non-Refundable)',
        'Customer harus menunjukkan kode voucher pada halaman "My Vouchers" pada aplikasi OVO kepada kasir ketika melakukan redeem',
      ],
      cara: [
        'Kalo ke Yoshinoya ajak sekalian temen kamu karena sekarang lagi ada paket Yummy Ber 3, yang isinya:\n- 2 Beef Bowl (Original/Yakiniku)\n- 1 Big Fried Chicken\n- 3 Ocha\n\nBisa kamu dapetin cuma Rp100.000 aja (normal Rp143.000).',
      ],
    },
    date: 'Berlaku Hingga 31 Dec 2019',
    minimalTransaction: null,
    cashback: null,
    kodePromo: null,
  },
  {
    title: 'Dummy - Craving for Sushi?',
    imageUrl: 'https://images-loyalty.ovo.id/public/deal/93/90/l/25025.jpg?ver=1',
    detailUrl: 'https://www.ovo.id/deals/view/25025',
    tags: ['ovo', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode promo 20 November - 20 Desember 2019.',
        'Setiap transaksi minimum Rp 10.000 menggunakan OVO Cash, berhak mendapatkan Cashback 40% dalam bentuk OVO Points.',
        'Maksimum cashback yang diberikan hingga 20.000 OVO points/Transaksi dan 40.000 OVO Points/ID selama periode promo (1 OVO Points = Rp 1).',
        'OVO berhak untuk membatalkan OVO Points yang telah diberikan apabila ditemukan kecurangan dalam pelaksanaan promo ini.',
        'Jika terjadi kegagalan transaksi OVO karena alasan teknis apapun (baik EDC, jaringan koneksi atau aplikasi) maka kegagalan tersebut tidak akan menjadi tanggung jawab merchant. Konsumen wajib melakukan pelunasan pembayaran terhadap merchant ybs. ',
      ],
      cara: [
        'Lagi ngidam sashimi? Atau sushi roll? Tenang aja, sekarang di Genki Sushi lagi ada Cashback 40%. Yuk, nikmatin sushi yang fresh dan otentik ala Jepang di cabang:',
      ],
    },
    date: 'Berlaku Hingga 20 Dec 2019',
    minimalTransaction: 10000,
    cashback: 40,
    kodePromo: null,
  },
  {
    title: 'Dummy - Mau Diskon + Cashback? Ke Hypermart Aja!',
    imageUrl: 'https://images-loyalty.ovo.id/public/deal/85/80/l/19590.jpg?ver=1',
    detailUrl: 'https://www.ovo.id/deals/view/19590',
    tags: ['ovo', 'food'],
    detail: {
      syaratKetentuan: [
        'Periode 1 Oktober – 31 Desember 2019',
        'Berlaku untuk layanan hypermart online express',
        'Maksimal discount 10% senilai Rp 20.000/transaki/pelanggan/hari',
        'Tidak berlaku untuk produk susu anak dibawah 1 tahun, rokok dan minuman alkohol',
        'Periode 1-31 Oktober 2019',
        'Berlaku untuk layanan hypermart online express & reguler',
        'Minimal transaksi Rp 100.000 dengan OVO Cash',
        'Maksimal cashback 20% hingga 25.000 OVO points/transaksi/OVO ID dan hingga 50.000 OVO points/bulan/OVO ID',
        'Tidak berlaku untuk produk susu anak dibawah 1 tahun, rokok dan minuman alkohol',
      ],
      cara: [
        'Belanja puas dapat DISKON 10% + Cashback 20% untuk berbagai kebutuhan harian dan bulanan kamu! Yuk, segera serbu Hypermart terdekat.',
      ],
    },
    date: 'Berlaku Hingga 31 Dec 2019',
    minimalTransaction: 100000,
    cashback: 20,
    kodePromo: null,
  },
]
